import pymol
import os


def get_residue_ids_from_p2rank_predictions(pred_csv):
    """
        pred_csv (str): abs file path to a prediction.csv generated by p2rank
        return a sorted list of residues_id, for eg ['A_1', 'A_2'...]
    """
    import csv

    row_index = 0

    with open(pred_csv, 'r') as csv_f:
        csv_reader = csv.reader(csv_f, delimiter=',')

        for row in csv_reader:
            if row_index == 0:
                row_index += 1
                continue
            if row_index == 1:
                return row[9].strip().split(' ')


pdbs = sorted(os.listdir('pdb_f/scwrl_out/'))
binding_site_csvs = list(filter(lambda file: 'predictions' in file, os.listdir('predicted_binding_sites')))
count = 0

for pdb in pdbs:
    if count == 6:
        break
        print('processing', pdb)
    full_pdb_path = os.path.join('pdb_f/scwrl_out/', pdb)
    pymol.cmd.load(full_pdb_path)
    pdb_code = pdb.replace('.pdb', "")
    binding_site_csv = 'predicted_binding_sites/' + list(filter(lambda file: pdb in file, binding_site_csvs))[0]
    residue_ids = get_residue_ids_from_p2rank_predictions(binding_site_csv)
    residues = []

    for res_id in residue_ids:
        residue_ids.append(res_id.split('_')[-1])

    res_selection = '+'.join(residues)
    select_cmd = " ".join(["sele", "resid", res_selection])
    pymol.cmd.select(name=pdb_code + 'binding', selection=select_cmd)
    count += 1
